---
title: "Reporte_Hito1"
output:
  html_document: 
    number_sections: yes
    theme: spacelab
    toc: yes
    df_print: default
  pdf_document:
    toc: yes
editor_options: 
  chunk_output_type: inline
---

# Introducción

* Planteamiento del problema

* Motivación

El dataset escogido para el proyecto corresponde a información respecto a videojuegos recopilada de la plataforma Steam. Fue obtenido originalmente de [Kaggle](https://www.kaggle.com/nikdavis/steam-store-games).


# Exploración de datos

La descarga consta de 6 archivos, donde la información más importante respecto a los juegos se encuentra en `steam.csv`.

## Descripción

A continuación se describen los atributos de la tabla principal, `steam.csv`.

- **appid:** Identificador (único) de cada juego.
- **name:** Título del videojuego.
- **release_date:** Fecha de lanzamiento (formato AAAA-MM-DD).
- **english:** Si el juego fue lanzado o no en inglés (1 o 0).
- **developer:** Desarrolladores (separados con punto y coma en caso de haber más de uno).
- **publisher:** Distribuidores (separados con punto y coma).
- **required_age:** Edad mínima requerida para jugar, según rating PEGI UK (0 equivale a sin rating).
- **steamspy_tags:** Géneros a los que pertenece un juego según votación de la comunidad SteamSpy (separados con punto y coma).
- **achievements:** Número de logros que incluye el juego.
- **positive_ratings:** Cantidad de votos positivos otorgados.
- **negative_ratings:** Cantidad de votos negativos otorgados.
- **average_playtime:** Tiempo de juego promedio de los usuarios, en minutos.
- **median_playtime:** Mediana del tiempo de juego de los usuarios, en minutos.
- **owners:** Rangos estimados de la cantidad de usuarios que descargaron un juego.
- **price:** Precio estándar del juego (en GBP o libras esterlinas).

Adicionalmente, existen otros atributos que de forma similar a las compañías desarrolladoras y distribuidoras, se encontraban separadas con punto y coma, pero al ser una cantidad de opciones más reducida, se decidió pre-procesar los datos y, usando Python y la librería `pandas`, se transformaron los atributos en archivos csv adicionales compuestos por cada juego (identificado con su `appid` para permitir joins con la tabla original) y si éstos incluyen o no cierta característica, entre todas las opciones posibles. Corresponden a los siguientes:

- **platforms:** Plataformas (PC) soportadas. 
- **categories:** Características adicionales de los juegos, como soporte de tecnologías y cantidad de jugadores.
- **genres:** Géneros con los que se clasificó el juego.

## Análisis

- El dataset no contiene elementos vacíos (NaN).


# Preguntas y problemas

[¿Explicar más las ideas, o describir los factores más interesantes a asociar inicialmente?]

1. ¿Cómo ha evolucionado la cantidad de juegos que lanzan los desarrolladores en el tiempo? (usando la ventana de tiempo en la que tenemos datos)

2. ¿Cómo decidir que un juego es/será popular entre los jugadores?

3. ¿Qué factores afectan más en producir altos tiempos de juego? (cantidad de achievements o juegos multiplayer por ejemplo)

4. ¿Cuáles son los géneros de juegos indie que producen más engagement? (mayores playtimes y más owners)


# Anexos

[Acá irían los links a los archivos de GitHub con código, o directamente los chunks para producir los gráficos o stats si no son demasiado largos].
